version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - .:/opt/sca/sqan/
      - ./config/sqan.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl:/etc/nginx/ssl 
    ports:
      - 8000:80
      - 443:443
    # entrypoint: ["tail", "-f", "/dev/null"]
      
  mongo:
    image: mongo:4.0-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db
      #- ./mongodump:/opt/mongodump
    
  api:
    image: node:12
    volumes:
      - .:/opt/sca/sqan/
      - apimodules:/opt/sca/sqan/node_modules
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    working_dir: /opt/sca/sqan
    entrypoint: ["tail", "-f", "/dev/null"]
    # command: npm run start
    #command: sh -c "
    #  mkdir -p /opt/sca/var/log
    #  && node ./api/sqan.js
    #  "
    # DEBUG=express:* node ./api/sqan.js 
  ui:
    image: node:12
    volumes:
      - .:/opt/sca/sqan/
      - nodemodules:/opt/sca/sqan/ui/node_modules
    working_dir: /opt/sca/sqan/ui
    # keep the container running
    entrypoint: ["tail", "-f", "/dev/null"]
    # command: npm run builddev


    
volumes:
  nodemodules:
    external: true

  apimodules:
    external: true

